### ISSUE TITLE
Decision Tracker - Deployment Specification retrieval (Rest/Open Gitops)

### ISSUE THREAD

**Issue by ajcraig** [margo/specification#22]
**Update Feb 12th, 2025**
The Motion to utilize REST API functions to retrieve the desired state from the Workload Fleet Manager has been approved by the WG.

**UPDATE January 14, 2025**
This Issue is going for vote to approve the usage of REST API functions to retrieve the desired state. See link to the latest comment detailing out what is being voted on. 
https://github.com/margo/specification/issues/22#issuecomment-2588190847

**Purpose** 
The goal of this Issue is to establish a Margo member consensus decision on baseline technology utilized by a specification function. Finalizing this decision will enable the focus group to complete specification section, reference implementation, and test/compliance suite. 

**Proposal** 
Utilize Open Gitops patterns from device's management interface to monitor a device specific git repository and pull the workload deployment specification. This deployment specification is then utilized to apply the desired workloads and configuration. The workload orchestration software(WOS) is responsible for maintaining the device specific Git repository.
- Onboarding and securing the Gitops communication is assumed to be a function of the Rest API interface. See related issue for more detail (https://github.com/margo/specification/issues/21).

Response Options:

- [ ] Approve Proposal
- [ ] Reject Proposal - Provide reasoning for rejection
- [ ] Abstain from Vote - No strong opinion either way

@margo/approvers Please respond below and consolidate your company's response to a single reply. If additional information is needed to provide your response, please reach out.

**Comment by phil-abb** [comment]
@ajcraig Approve Proposal

**Comment by stormc** [comment]
git + the git repository is used as transport means to bring the desired state information artifact down to the device, that then acts on this data. In essence, this could've been done as well by curl'ing, e.g., a `.tar.gz` and unpacking + acting on it. So, git is used as transport mechanism. The git repo contents are the desired state artifact. The device is always just the consumer/reader of this data and never writes. It regularly polls or gets push-informed by some other service about changes in the git repository.

Now, I think we can agree on the need to have an artifact blob transfer facility in the device's direction, be it curl or git to stay in the picture. If both can do (basically) the same thing, then we may abstract from the particularities to enable choice (here: either git or curl). So, we may make an interface that can be implemented with/by either.

To make this more practical, consider this example: The URL of the state information is configured via REST (see #22). A simple binary (could be a shell script) `/usr/bin/margo_getstate` is called with this URL and possibly other parameters (to be seen) and embodied in this script is the git or curl magic. This way, one can hook up existing blob delivery systems into margo without much effort (e.g., using mercurial instead of git). If using git, there may be `/usr/bin/margo_getstate log` giving more status because a git repository has richer metadata to be extracted from than a simple curl'd download. This could be optional in the interface specification while the basics are mandatory.

So, I'm in favor of having such a mechanism but I do think it's a low-hanging fruit to abstract from git to enable choice and a wider variety of implementations for easier integration of margo into existing deployments. That said, I'm fine with using git for the blueprint reference implementation.

**Comment by phil-abb** [comment]
@stormc It's not clear to me how this would work because if we provide multiple was of implementing this the WOS vendor could choose one way and the device vendor another way that isn't compatible.

Maybe I'm just misunderstanding what you're meaning.

**Comment by stormc** [comment]
Good point, @phil-abb. Granted, the WOS and the device(s) need to be on the same page. When the device is registered to a WOS, i.e., provisioned, one may install the according interface implementation (package). At this point, this is known. You can also do this while device onboarding – if hooking to a WOS is done in this step. Or you know what WOS you will be hooked up to and pre-load the interface implementation (package). If you need to change this later on in the device's lifetime, it's just a (firmware) update away or you may trigger the package installation of this new interface implementation by the WOS if we'd like to have an API endpoint for that (aka device management binding).  So, there are ways to have/keep the WOS and device(s) on the same page..

This doesn't mean we shouldn't set on a default interface implementation (e.g., git) with which you don't have all these things to consider. But it makes it possible to deviate in a manageable way from margo's proposed default which puts you in custom engineering land in which you have to sort out these things – which is fine as you can like outlined above.
In essence, this indirection doesn't cost us much in spec/implementation and users get options, and having options is always good :)

**Comment by ajcraig** [comment]
> Good point, @phil-abb. Granted, the WOS and the device(s) need to be on the same page. When the device is registered to a WOS, i.e., provisioned, one may install the according interface implementation (package). At this point, this is known. 

Installing interface implementation (package) after manufacturing was something that Schneider raised as a concern early on. This was the reason we brought the interface into scope to ensure the device manufacturers can secure their devices at manufacturing. 


> You can also do this while device onboarding – if hooking to a WOS is done in this step. Or you know what WOS you will be hooked up to and pre-load the interface implementation (package).

the Interface implementation should be the Margo Compliant interface that we define in the specification. This should be tested and verified during manufacturing to ensure Margo compliance before put on a shelf for purchasing by end users. Purpose built devices, utilizing WOS specific interfaces is not aligned with Margo's overall goals. 

> If you need to change this later on in the device's lifetime, it's just a (firmware) update away or you may trigger the package installation of this new interface implementation by the WOS if we'd like to have an API endpoint for that (aka device management binding). So, there are ways to have/keep the WOS and device(s) on the same page..

The goal of Margo is to not have to comply with the various offerings in the field, our goal is to create the interface standard that is built in all Margo compliant devices and orchestrators from manufacturing. 

> This doesn't mean we shouldn't set on a default interface implementation (e.g., git) with which you don't have all these things to consider. But it makes it possible to deviate in a manageable way from margo's proposed default which puts you in custom engineering land in which you have to sort out these things – which is fine as you can like outlined above. In essence, this indirection doesn't cost us much in spec/implementation and users get options, and having options is always good :)

I don't understanding what you mean by “Default” implementation. We are prescribing exact interface / methods / infrastructure both WOS and device need to comply with for Margo Compliance. If we leave the market with many options I fear we are not complying with the Margo initiative’s main goal. To standardize on a single way of doing things to ensure interoperability without headaches.

**Comment by stormc** [comment]
> > Good point, @phil-abb. Granted, the WOS and the device(s) need to be on the same page. When the device is registered to a WOS, i.e., provisioned, one may install the according interface implementation (package). At this point, this is known.
> 
> Installing interface implementation (package) after manufacturing was something that Schneider raised as a concern early on. This was the reason we brought the interface into scope to ensure the device manufacturers can secure their devices at manufacturing.

No problem: Just stick to the one we as margo denote as standard. Given your WOS is not customized in this regard and doesn't use git, it all works. If, however, the WOS uses a different transport method, then you're in custom engineering land and you have to adapt the (e.g. Schneider) device. However, with this ability, it is at all possible in the first place to hook margo into environments that would otherwise remain closed to margo application. It's about options and flexibility.

> > You can also do this while device onboarding – if hooking to a WOS is done in this step. Or you know what WOS you will be hooked up to and pre-load the interface implementation (package).
> 
> the Interface implementation should be the Margo Compliant interface that we define in the specification. This should be tested and verified during manufacturing to ensure Margo compliance before put on a shelf for purchasing by end users. Purpose built devices, utilizing WOS specific interfaces is not aligned with Margo's overall goals.

They are: We set the interface any implementation has to follow whether that uses git or something else under the hood. Staying in the picture of the `/usr/bin/margo_getstate` binary above we define the command line options that must be sensibly implemented. What this implementation then does (`curl http://...` or `git pull`) is a different thing.

> > If you need to change this later on in the device's lifetime, it's just a (firmware) update away or you may trigger the package installation of this new interface implementation by the WOS if we'd like to have an API endpoint for that (aka device management binding). So, there are ways to have/keep the WOS and device(s) on the same page..
> 
> The goal of Margo is to not have to comply with the various offerings in the field, our goal is to create the interface standard that is built in all Margo compliant devices and orchestrators from manufacturing.

Yes, and this is the margo denoted standard. However, making such an interface eases the adoption of margo or makes it possible in the first place for environments that can't fully comply (for whatever reason). With this, and introducing interfaces in other places where it doesn't hurt us much or contradict margo's ideas, we're widening the applicability of margo, which is in margo's very interest.

> > This doesn't mean we shouldn't set on a default interface implementation (e.g., git) with which you don't have all these things to consider. But it makes it possible to deviate in a manageable way from margo's proposed default which puts you in custom engineering land in which you have to sort out these things – which is fine as you can like outlined above. In essence, this indirection doesn't cost us much in spec/implementation and users get options, and having options is always good :)
> 
> I don't understanding what you mean by “Default” implementation. We are prescribing exact interface / methods / infrastructure both WOS and device need to comply with for Margo Compliance.

Yes, and we continue to do so. We're just not dictating the implementation of this interface. We're advocating / proposing the default margo way, but you may deviate in implementation, not in specification. This is what we do with the reference implementation as well: You can take it or create your own as long as it's a drop-in for the reference.

> If we leave the market with many options I fear we are not complying with the Margo initiative’s main goal. To standardize on a single way of doing things to ensure interoperability without headaches.

Options in implementation, not option in compliance or deviating from the standard.

**Comment by tomcounihan** [comment]
Thinking about this more. Conversation I've picked up so far is at the 'transport' layer - getting the yaml do the device. And in that sense I see the abstraction argument. However if we go down the abstract approach, would we also not need to address versioning? Intuitively, when I use tools like ArgoCD in a different context, what I get is both the 'transport' and the application of the artifact with tool/knobs to be exact in what version I'm interested in applying - both rolling forward and backwards. With a curl approach, you might have to layer on top some naming convention to achieve the same thing - no? I guess what I'm saying is, leaveling the topic as abstract from exclusively a transport layer consideration without considering the versioning of app specs and how to control how to target them to specific devices may leave some ambiguity from an interop perspective. Hope I'm making sense. T.

**Comment by phil-abb** [comment]
@tomcounihan If I'm understanding what you're saying this is why I favor adopting git for this part. Git does several additional things besides just being able to download files.  As you mentioned git handles versioning and keeping a change history on the server but it also has benefits on the client side:
- With git, it's easy to see if changes need to be pulled down so you know when changes are made to the desired state. 
- It works with just the file diffs so what you pull down is smaller. 
- It pulls the updates for all the files in the branch. 
- There are tools, such as ArgoCD, available that work with git to manage applying the desired state 
- There are several open-source git client libraries to use in the code. 
- There are open-source git servers available.

If we try to abstract away from this our abstraction must account for all this functionality. I see this as a case of not re-inventing the wheel. If something is available that solves problems we need to solve then it makes sense to use it if it meets our needs.

Also, there are enough examples of open source git servers and clients, plus the details from [Git](https://git-scm.com/book/en/v2) on how to implement them, if someone needed to they could technically implement their own.

**Comment by MarkRiddoch** [comment]
Sorry, had to drop from the call before I got a chance to express a view. I understand the gitops concept has major benefits, my personal viewport would be to move this functionality away from the edge device to the WOS as this way we can reduce the complexity of the edge device, reduce the diversity of protocols between the edge device and the WOS. If we want to have flexibility to use different solutions, other than a pure git repository, we only need to do this in one place, the WOS. I think it also has long term support benefits as it lets us change the version management mechanisms and support later git protocols (or others) in the WOS without having to touch all of the edge devices.

**Comment by phil-abb** [comment]
@MarkRiddoch Did you have a specific behavior in mind? 

If we said there was one API that returned all the new desired state files for the device when called then I could see something like this:
- Device calls WOS with a hash indicating the device's current state: GET /device/{deviceId}/desiredState?currentStateHash=123ABC
- If there were no changes to the desired state since the currentStateHash 123ABC then nothing is returned by the WOS
- If there were changes to the desired state then just the files that were changed between the new desired state hash and the old 123ABC hash are returned along with the updated current desired state hash.
- If no currentStateHash is provided then all the files are returned along with the most recent desired state hash

I guess technically the device could have a git repo locally that it's using. When it receives the files from the WOS it could push the files into its local git repository. Then something like FluxCD or ArgoCD could monitor the local repo on the device if someone wanted to use those tools on the device

**Comment by eriknordmark** [comment]
As I offered on the call, there is one (actually two) examples of how a RESTful (in the sense of representational state transfer, not the semantics of POST vs GET etc) interaction between the WOA and WOS for efficiently checking and fetching the manifests for one or more workloads. 

Note that this doesn't intend to get into the details of what's in the margo manifest; it merely assumes that a sha256 can be calculated over the string or strings which make up the manifest.

To illistrate the idea with these examples the payload is in json format, but that could alternatively be coap or protobuf.

# Simplest form - very similar to Phil's suggestion above

POST to https://{server}/api/woa/{device-id}/desired-workload-config
Payload
```
{ "config-hash": "bbd98359f85a074b4a89c8238edd2247e9b6443a1bc2fc815e73802e2739523e"}
```
(Alternatively this could be a HTTP GET with  the If-None-Match http header containing the hash, with the response including an ETag http header with the current/new hash.)

The if there is no change to any of the workloads for the device, the response would be a http 303 'not modified' and no payload. But if there was a change to at least one (including an add or delete of a workload), the response code would be 200 with the payload being the complete set of workloads identified by their UUID e.g.,
```
{ 
  "config-hash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", 
  "workloads": [
    {
      "id": "e4a29f04-e8bd-4912-8fc2-1282d1c3ffc9",
      "manifest": "margo yml for app1"
    },
    {
      "id": "a74e390c-9a77-4af8-94b7-2a4891038c1d",
      "manifest": "margo yml for app2"
    }
  ]
}
```

Of course, the manifests would be a lot more voluminous.

# More efficient - only send workload(s) which changed

If the device has already received the manifests for two workloads, then it would periodically poll the WOA with a
POST to https://{server}/api/woa/{device-id}/desired-workload-config
Payload
```{
  "config-hash-list": [
    {
      "id": "e4a29f04-e8bd-4912-8fc2-1282d1c3ffc9",
      "manifest-hash": "13b4f1cc8ba01ec9a2f8d7f4690a35e2d8dc753ab757c97a11b8a8dec736414c"
    },
    {
      "id": "a74e390c-9a77-4af8-94b7-2a4891038c1d",
      "manifest-hash": "b7abf929a82f08d0df8b82257ebedb52c0c9f6704a314518b11822107d6001f0"
    }
  ]
}
```

If no change to any workload manifest, the response would be a http 303 'not modified'  with no payload. 

If e.g., app2 change the response would be a complete set of hashes but only the manifest for app2
```{
  "config-list": [
    {
      "id": "e4a29f04-e8bd-4912-8fc2-1282d1c3ffc9",
      "manifest-hash": "13b4f1cc8ba01ec9a2f8d7f4690a35e2d8dc753ab757c97a11b8a8dec736414c"
    },
    {
      "id": "a74e390c-9a77-4af8-94b7-2a4891038c1d",
      "manifest-hash": "0a46b110863d99903fcd0b947cc97c6f281ef8ecd6a5a072dec7aac7d9b18b96",
      "manifest": "new yml for app 2"
    }
  ]
}
```

And if app1 was deleted but no change to app2 the response would have been 
```{
  "config-list": [
    {
      "id": "a74e390c-9a77-4af8-94b7-2a4891038c1d",
      "manifest-hash": "b7abf929a82f08d0df8b82257ebedb52c0c9f6704a314518b11822107d6001f0"
    }
  ]
}
```

**Comment by phil-abb** [comment]
@eriknordmark Thanks for the examples.

One important part of your example is highlighting how to deal with deleting applications. Showing the absence of something would be impossible if we only return files that changed. So, as you are showing here, we need to do something more than send files back.

Also, I'm interested in understanding why you have hashes for each file instead of a single hash representing the state at a point in time.

So for example, if we relate this to Git, the device could send a request saying the last commit I pulled down was ` f9c8f75cbfd1c81a19ae48e89541405ecaa16b8f` then the WOS can see what has changed since then using `git diff`

```
git diff --name-status f9c8f75cbfd1c81a19ae48e89541405ecaa16b8f
M       complex-example/appdeployment.yaml
M       hello-world/appdeployment.yaml
D       simple-service/appdeployment.yaml
```

Also, what are your thoughts about this needing to be an asynchronous call? It seems like there is the potential for it to take a while (relatively speaking) for the WOS to process and prepare the payload to send back.

**Comment by g0zilla** [comment]
> One important part of your example is highlighting how to deal with deleting applications. Showing the absence of something would be impossible if we only return files that changed. So, as you are showing here, we need to do something more than send files back.

Shouldn't be too much of a problem. The response could be.

```json
  "config-list": [
    {
      "id": "e4a29f04-e8bd-4912-8fc2-1282d1c3ffc9",
      "deleted": true
    },
    {
      "id": "a74e390c-9a77-4af8-94b7-2a4891038c1d",
      "manifest-hash": "b7abf929a82f08d0df8b82257ebedb52c0c9f6704a314518b11822107d6001f0"
    }
  ]
}
```

On subsequent requests, the entry for e4a... could be removed.

> 
> Also, I'm interested in understanding why you have hashes for each file instead of a single hash representing the state at a point in time.
> 
> So for example, if we relate this to Git, the device could send a request saying the last commit I pulled down was ` f9c8f75cbfd1c81a19ae48e89541405ecaa16b8f` then the WOS can see what has changed since then using `git diff`
> 

> Also, what are your thoughts about this needing to be an asynchronous call? It seems like there is the potential for it to take a while (relatively speaking) for the WOS to process and prepare the payload to send back.

Fetching a state shouldn't take too much time even if there is a little bit of payload because of the yamls (a few KB). Typical HTTP timeouts are between 10 and 30 seconds. If we need more, we could specify timeouts of minutes or hours (but then async would make more sense). We could introduce also a `...?quick_answer=true` flag as optional query parameter. In that case, only that something is changed would be shown. 

**What is your opinion about propagating back the state of the workload to the WOS?** E.g, the WOS should learn if a workload is completely deployed, whether there is an error and so on ... Afaik, the OTEL protocols are not the right candidate for this (only telemetry, no r/t, unreliable). Should the WOA offer also a REST interface or should it push the current state in fixed intervals?

If app lifecycle operations like "deploy an app on the edge device" are also in scope, we need asynchronous requests. E.g., deploying an app takes several minutes. You don't want to block threads on the WOS for that long.

**Comment by stormc** [comment]
> What is your opinion about propagating back the state of the workload to the WOS?

For anything more involved than simple `get <INFO>`, `put <INFO>` etc. interactions, it quickly becomes complicated as you're effectively modeling an interaction protocol requiring coordination among the parties, i.e., they need to go through the interaction protocol (aka workflow) in lock step for global view/state consistency.

This is exactly what we're using [wfx](https://github.com/siemens/wfx) for in SIEMENS products, TL;DR: as long as you can come up with a state machine describing your workflow, you can execute that workflow in a coordinated manner among the wfx and its clients. Examples are, among others, [wfx: Software Update / Device Artifact Update](https://github.com/siemens/wfx/tree/main/workflow/dau) and our use case here, [wfx: config deployment workflow](https://github.com/siemens/wfx/tree/main/contrib/config-deployment).

**Comment by phil-abb** [comment]
@g0zilla 
>What is your opinion about propagating back the state of the workload to the WOS? 

Currently, the specification indicates the [deployment status](https://specification.margo.org/margo-api-reference/workload-api/device-api/deployment-status/) must be returned when the device is applying the desired state. Does this cover what you're thinking or do you feel there is more to it than just the deployment status?

**Comment by tomcounihan** [comment]
> @g0zilla
> 
> > What is your opinion about propagating back the state of the workload to the WOS?
> 
> Currently, the specification indicates the [deployment status](https://specification.margo.org/margo-api-reference/workload-api/device-api/deployment-status/) must be returned when the device is applying the desired state. Does this cover what you're thinking or do you feel there is more to it than just the deployment status?

@phil-abb - just a thought. There might be some merit to researching what either/or/both FluxCD/ArgoCD report as state. This is not to advocate their adoption, rather it seems to me that these are mature solutions that have history in applying to k8s - so I suspect their has been thought and energy already in figuring out what makes sense as state, then ergo a state machine? just a though....

**Comment by phil-abb** [comment]
@tomcounihan 

> @phil-abb - just a thought. There might be some merit to researching what either/or/both FluxCD/ArgoCD report as state

Yeah, that's a good suggestion

**Comment by eriknordmark** [comment]
> One important part of your example is highlighting how to deal with deleting applications. Showing the absence of something would be impossible if we only return files that changed. So, as you are showing here, we need to do something more than send files back.

That is why my example sends a complete config-list each time (unless nothing changed and you get a 303 response).
The absence of an item in that list is the indication that it should not exist on the device.

A flag like "deleted" is more complex when there is intermittent and unknown connectivity; for how long would the WOS need to include a hash with "deleted" set? The declarative approach of including everything avoids such concerns.

> Also, I'm interested in understanding why you have hashes for each file instead of a single hash representing the state at a point in time.

The simplest approach has a single hash for all of the workflows.
But that means that if something changed in workflow/app1 (or you added app3) you would need to include the complete manifest for the unchanged app2 as well, and the WOA would  need to compare the manifest content for app2 to detect that it didn't change.
Thus the more efficient way is to have a hash per workflow - saves work in the WOA and less bytes to send when there is a change to one workload.

> So for example, if we relate this to Git, the device could send a request saying the last commit I pulled down was ` f9c8f75cbfd1c81a19ae48e89541405ecaa16b8f` then the WOS can see what has changed since then using `git diff`
> 
> ```
> git diff --name-status f9c8f75cbfd1c81a19ae48e89541405ecaa16b8f
> M       complex-example/appdeployment.yaml
> M       hello-world/appdeployment.yaml
> D       simple-service/appdeployment.yaml
> ```

Sure, that works. But I haven't run a tcpdump to see how many packets and roundtrips it takes to do a git pull.

> Also, what are your thoughts about this needing to be an asynchronous call? It seems like there is the potential for it to take a while (relatively speaking) for the WOS to process and prepare the payload to send back.

Since 99.99% of the time the device polls there would be no change (in production the workloads might change a few per year and the device might poll for changes every few minutes), it wouldn't make sense to have the WOA have to deal with async RESTful patterns but instead have the WOS do the work. One way to implement this is to have the WOS save the most recent configuration it sent to the device (basically the hash/hashes in my example) and when the WOS detects up update in its backend (which could be git or some database) it would trigger re-generating the complete workload config for the device, and the next poll from the device will return the new config.

**Comment by g0zilla** [comment]
> Currently, the specification indicates the [deployment status](https://specification.margo.org/margo-api-reference/workload-api/device-api/deployment-status/) must be returned when the device is applying the desired state. Does this cover what you're thinking or do you feel there is more to it than just the deployment status?

> 

With returned, you mean that the device will call the Device API at the WOS, right? (This is how I understood the Deployment Status doc.) The specification doesn't tell something about the interaction pattern. I guess, it should send the status in regular intervals.

**Comment by phil-abb** [comment]
@g0zilla 
> With returned, you mean that the device will call the Device API at the WOS, right? (This is how I understood the Deployment Status doc.) The specification doesn't tell something about the interaction pattern. I guess, it should send the status in regular intervals.

[This section](https://specification.margo.org/orchestration/workload/workload-deployment/) talks about the workflow for sending the deployment status. What has been discussed up to this point is sending the status to the WOS while the desired state is being applied and after it completes. We haven't discussed sending any messages to the WOS about status when it's in a static state.

**Comment by phil-abb** [comment]
@eriknordmark 
> Sure, that works. But I haven't run a tcpdump to see how many packets and roundtrips it takes to do a git pull.

I was thinking of Git used by the WOS as the file storage mechanism behind the scenes. If this was how they chose to implement things then sending the individual hashes for each file wouldn't be needed because they can see what has changed between the commit hash the device says it has and the latest commit. 

So, in this case:
```
git diff --name-status f9c8f75cbfd1c81a19ae48e89541405ecaa16b8f
M       complex-example/appdeployment.yaml
M       hello-world/appdeployment.yaml
D       simple-service/appdeployment.yaml
```

The WOS would know it needs to send the complex-example/appdeployment.yam and hello-world/appdeployment.yaml files since they were both modified and indicate the simple-service/appdeployment.yaml file was deleted.

If instead the device's hash was even older than when the the simple-service app was first deployed:
```
git diff --name-status c40ab93ea3c2599210d8d060fcfd52be0102ca14
A       complex-example/appdeployment.yaml
M       complex-example/appdeployment.yaml
```
The WOS would know to send the complex-example/appdeployment.yaml file added and the complex-example/appdeployment.yaml file updated and the simple-service/appdeployment.yaml would never get sent to the device because as far as the device knew this was never even deployed.

**Comment by eriknordmark** [comment]
> The WOS would know it needs to send the complex-example/appdeployment.yam and hello-world/appdeployment.yaml files since they were both modified and indicate the simple-service/appdeployment.yaml file was deleted.

Sure, but such a "deleted" notification is imperative and not declarative, hence makes lots of assumptions. In this particular implementation (using a git backend for storage with infinitely old/long history) it can determine that it needs to tell the device that simple-service/appdeployment.yaml relative to the hash received from the device. But given that a device might be a spare sitting powered off somewhere for a year or more, such an API to the device would require that the WOS implementation have infinite history of all previous hashes. That seems like unnecessary coupling between the API and the WOS implementation.

**Comment by phil-abb** [comment]
@eriknordmark 
>Sure, but such a "deleted" notification is imperative and not declarative, hence makes lots of assumptions...

Fair, and interesting, point :thumbsup:

**Comment by phil-abb** [comment]
@margo/technical-wg There were some questions about how big the desired state git repo could get. I created a basic script that can simulate this for people who are concerned/interested. It's not a perfect simulation but gets you in the ballpark and is better than guessing or assuming.

It uses this [application deployment yaml](https://github.com/margo/End-To-End-Prototypes/blob/pdp/go-prorotype/install/examples/complex-example-k8s-app-deployment.yaml) example file as a template.

You can get the script from the [woa-interface-wg](https://github.com/margo/woa-interfaces-wg/tree/main/git-repo-simulator) repository.

Feel free to fix, modify, or improve it as you see fit.

**Comment by phil-abb** [comment]
> There were some questions about how big the desired state git repo could get...

[Here](https://urldefense.com/v3/__https://lists.margo.org/g/technical-wg/files/Git*20repo*20size*20demo.mp4__;JSUl!!NLW3fF9v!O_aNK2-u3Qr8pr-Mab1x1Q1Edv3KUaEEwhXEXhwNnoxWGFU29h2POD3jZJtjJONhqAClZvgQM4h8hbrvBEoHwFKl$) is demo recording showing this and a few other things related to the desired state Git repo size and full vs shallow clones.

**Comment by phil-abb** [comment]
@eriknordmark 
> Sure, that works. But I haven't run a tcpdump to see how many packets and roundtrips it takes to do a git pull.

I uploaded some [tcpdump files](https://github.com/margo/woa-interfaces-wg/tree/main/git-repo-simulator/tcpdump) that go alone with the demo ⬆️

**Comment by ajcraig** [comment]
@margo/approvers Following our call on Tuesday January 7th, we decided as a group that REST API functions shall be used by the management interface client for retrieving the desired state specification from the management interface server.

This provides implementation freedom to the Workload Fleet Managers regarding the storage and maintenance of the desired state files in the back end, along with standardizing on a single RESTful interface for both "Cloud to Edge" and "Edge to Cloud" functions via the Margo Management Interface.

**Note:** We are still discussing how the API would look and act. We have written up a few proposals to accomplish this but there may be other ideas:
https://github.com/margo/woa-interfaces-wg/tree/main/git-alternatives/proposals

Prototype of this can be found in the following location:
https://github.com/margo/woa-interfaces-wg/tree/main/git-alternatives/prototypes

Response Options:

- [x] Approve Proposal to utilize REST API functions to retrieve the desired state from the Workload Fleet Manager
- [ ] Reject Proposal - Provide reasoning for rejection
- [ ] Abstain from Vote - No strong opinion either way

**Comment by phil-abb** [comment]
Approve Proposal to utilize REST API functions to retrieve the desired state from the Workload Fleet Manager

**Comment by stormc** [comment]
[x] Approve Proposal to utilize REST API functions to retrieve the desired state from the Workload Fleet Manager on behalf of SIEMENS.

**Comment by james-teal** [comment]
Approve Proposal to utilize REST API functions to retrieve the desired state from the Workload Fleet Manager

**Comment by adamqiu-emerson** [comment]
On behalf of Emerson
- [x] Approve Proposal to utilize REST API functions to retrieve the desired state from the Workload Fleet Manager

**Comment by merrill-harriman-se** [comment]
On behalf of Schneider Electric:

Approve Proposal to utilize REST API functions to retrieve the desired state from the Workload Fleet Manager

**Comment by eriknordmark** [comment]
On behalf of ZEDEDA
 Approve Proposal to utilize REST API functions to retrieve the desired state from the Workload Fleet Manager

**Comment by effndc** [comment]
on behalf of Intel

- [x] Approve Proposal to utilize REST API functions to retrieve the desired state from the Workload Fleet Manager

**Comment by srberard** [comment]
On bahalf of Atym
- [X] Approve Proposal to utilize REST API functions to retrieve the desired state from the Workload Fleet Manager

**Comment by ajcraig** [comment]
The Motion to utilize REST API functions to retrieve the desired state from the Workload Fleet Manager has been approved by the WG.
